services:
  postgresDB:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ${PWD}/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: nextjs-dev
    build:
      context: ./ai-next-rag
      dockerfile: Dockerfile  
      target: dev
    restart: always
    command: npm run docker:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - postgresDB
    volumes:
      - /app
      - /app/node_modules
